name: Design System

# where to not look for files

excludeDir:
  - dist

# these resources are always mirrored in the generated style guide

assets:
  - static

# customize the style guide; these resources are exclusivly for the style guide itself, not the
# components presented in the guide
#
# for a list of class hooks: https://github.com/nextbigsoundinc/stylemark#theming

# theme:
#   logo: path/to/logo.jpg
#   css:
#     - path/to/styles.css
#   js:
#     - path/to/script.js

# add additional resources to all generated example components

examples:
  css:
    - https://unpkg.com/camp-css@latest/css/camp.min.css
    - static/main.min.css
  js:
    - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.js


# custom order the items in the sidebar

order:
